"""Pipelock action receipt verifier.

Verifies Ed25519-signed action receipts emitted by the Pipelock mediator.
Matches the Go reference implementation in ``internal/receipt`` byte-for-byte
so that receipts generated by the Pipelock binary verify identically in Go
and Python.

Typical usage::

    import pipelock_verify

    # Single receipt from a JSON string, bytes, or already-parsed dict.
    result = pipelock_verify.verify(receipt_json)
    if not result.valid:
        raise SystemExit(f"bad receipt: {result.error}")

    # Receipt chain from a flight recorder JSONL file.
    chain = pipelock_verify.verify_chain("evidence-proxy-0.jsonl")
    if not chain.valid:
        raise SystemExit(f"chain broken at seq {chain.broken_at_seq}: {chain.error}")

Trust anchors are opt-in. Pass ``public_key_hex`` to pin a specific signer,
or leave it empty to trust the key embedded in the receipt (chain mode then
enforces signer consistency across every receipt in the file).

Wire format: see https://pipelab.org/learn/action-receipt-spec/ for field
layout, canonicalization rules, and the exact signing input. The format is
the Go ``json.Marshal`` output of the ``Receipt`` struct; this library
mirrors it.
"""

from ._verify import (
    ChainResult,
    InvalidReceiptError,
    VerifyResult,
    verify,
    verify_chain,
)

__version__ = "0.1.0"

__all__ = [
    "ChainResult",
    "InvalidReceiptError",
    "VerifyResult",
    "__version__",
    "verify",
    "verify_chain",
]
